ff_platform_home:
    path:     /{page}
    defaults:
        _controller: ffPlatformBundle:Advert:index
        page:
    requirements:
        page: \d*

ff_platform_view:
    path:     /advert/{id}
    defaults:
        _controller: ffPlatformBundle:Advert:view
    requirements:
        id: \d+

ff_platform_add:
    path:     /add
    defaults:
        _controller: ffPlatformBundle:Advert:add

ff_platform_edit:
    path:     /edit/{id}
    defaults:
        _controller: ffPlatformBundle:Advert:edit
    requirements:
        id:     \d+

ff_platform_delete:
    path:    /delete/{id}
    defaults:
        _controller: ffPlatformBundle:Advert:delete
    requirements:
        id:    \d+